### ISSUE TITLE
Astro Diagram Not Working Returning False

### ISSUE THREAD

**Issue by Ravikisha** [JulianCataldo/web-garden#88]
I am trying to use Astro Diagram module for implementing the mermaid module in my astro project and when i add this module and try to add a block of markdown code 
```markdown
```mermaid
graph TD
A-->B
```
this retuns false. There is no diagram

**Comment by stigi** [comment]
I can confirm. Ran into the same issue and applying the fix from c0ffc3149beeb1d34c4e152bb774c33cff0b20d7 solved the issue. Am running it as a patch until the next release 👍
